# Eat Safe, Love

## Notebook Set Up

In [18]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [149]:
# review the collections in our database
print(mongo.list_database_names())

['Class_db', 'admin', 'autosaurus', 'classDB', 'config', 'epa', 'fruits_db', 'gardenDB', 'local', 'met', 'travel_db', 'uk_food']

In [150]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [122]:
# Find the establishments with a hygiene score of 20
query = { 'scores.Hygiene': 20}

# Find the establishments with a hygiene score of 20

# # Use count_documents to display the number of documents in the result
score20_result = establishments.count_documents({'scores.Hygiene': 20})
score20_result
# Display the first document in the results using pprint
pprint(score20_result)

41

In [123]:
query = { 'scores.Hygiene': 20}
results = establishments.find_one(query)
pprint(results)
i = 0
for  result in results:
     if i < 5 : 
          pprint(result)

     i = i+1

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatigValue': 0,
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64a9b3f3c5b10300e78adf59'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
'_id'
'FHRSID'
'ChangesByServerID'
'LocalAuthorityBusinessID'
'BusinessName'

In [58]:

#result_df = pd.DataFrame.from_records(score20_result)
# Display the number of rows in the DataFrame

# Display the first 10 rows of the DataFrame

# Convert the result to a Pandas DataFrame
results = establishments.find(query)
score20_result = list(results)
result_df = pd.DataFrame(score20_result)

result_df.head(3)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,64a9b3f3c5b10300e78adf59,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,64a9b3f3c5b10300e78ae2d8,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,64a9b3f3c5b10300e78ae5e4,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [86]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
#query= {'LocalAuthorityName': {'$in': ['London']},'RatingValue': {'$gte' :4}}

query = {'LocalAuthorityName': {'$regex':'London'}, 'RatingValue': {'$gte': 4}}
score20_result_gte4 = establishments.find(query)

# score20_result_gte4 = establishments.count_documents( {'LocalAuthorityName': {'in$': ['London']},{'RatingValue': {'$gte' :4}})

# Use count_documents to display the number of documents in the result
#score20_result_gte4 = list (establishments.find(query))
count_result = establishments.count_documents(query)
count_result

33

In [137]:
# Display the first document in the results using pprint

query = {'LocalAuthorityName': {'$regex':'London'}, 'RatingValue': {'$gte': 4}}
results_London = establishments.find_one(query)

# if i did not use find_one answer return with full details
pprint(results_London)
# for result in results_London:
#      pprint(result)

{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatigValue': 4,
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64a9b3f3c5b10300e78af975'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [140]:
# Convert the result to a Pandas DataFrame

results_London = establishments.find(query)
# df2 = list(results_London)
results_London_df = pd.DataFrame(results_London)



# Display the number of rows in the DataFrame
rows = len(results_London_df)
print("Number of rows in DataFrame:", rows)

# results_London_df.head()
results_London_df.head(10)


# Display the first 10 rows of the DataFrame

Number of rows in DataFrame: 33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude,RatigValue
0,64a9b3f3c5b10300e78af975,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,4
1,64a9b3f3c5b10300e78afc98,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
2,64a9b3f3c5b10300e78b07e6,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,4
3,64a9b3f3c5b10300e78b15e4,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
4,64a9b3f3c5b10300e78b15e6,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
5,64a9b3f3c5b10300e78b1cf0,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
6,64a9b3f4c5b10300e78b3dff,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
7,64a9b3f4c5b10300e78b41c7,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,4
8,64a9b3f4c5b10300e78b41dc,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5
9,64a9b3f4c5b10300e78b41e0,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,5

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [142]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.369321
longitude = 0.508551

query = {'geocode.latitude': {'$gte':latitude-degree_search, '$lte':latitude+degree_search}, 
         'geocode.longitude': {'$gte': longitude-degree_search, '$lte': longitude+degree_search},
         'RatingValue': 5}
sort = [('score.Hygiene', 1)]
limit = 5

# Print the results
pprint(list(establishments.find(query).sort(sort).limit(limit)))

[{'AddressLine1': '108 Pattens Lane',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'Sealand Fish And Chips',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4627.071735597095,
  'FHRSID': 802088,
  'LocalAuthorityBusinessID': 'PI/000251174',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RA',
  'RatigValue': 5,
  'RatingDate': '2022-03-01T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64a9b3f3c5b10300e78af77f'),
  'geocode': {'latitude': Decimal128('51.366737'),
              'longitude': Decimal128('0.516021')},
  'latitude': None,
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/802088',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 0}},
 {'AddressLine1': '110 Pattens Lane',
  'AddressLine2': 'Rochester',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'News Shop',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4627.071735597095,
  'FHRSID': 786158,
  'LocalAuthorityBusinessID': 'PI/000030142',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RA',
  'RatigValue': 5,
  'RatingDate': '2017-09-12T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64a9b3f3c5b10300e78af780'),
  'geocode': {'latitude': Decimal128('51.366737'),
              'longitude': Decimal128('0.516021')},
  'latitude': None,
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/786158',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': 'The Huntsman PH',
  'AddressLine2': 'The Huntsman',
  'AddressLine3': '106 Pattens Lane',
  'AddressLine4': 'Rochester',
  'BusinessName': 'The Huntsman',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4627.068948009548,
  'FHRSID': 510152,
  'LocalAuthorityBusinessID': 'PI/000243002',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RA',
  'RatigValue': 5,
  'RatingDate': '2022-02-20T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64a9b3f3c5b10300e78af77d'),
  'geocode': {'latitude': Decimal128('51.3666861'),
              'longitude': Decimal128('0.5160458')},
  'latitude': None,
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/510152',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '27-31 Pattens Lane',
  'AddressLine2': 'Chatham',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'Co-Op',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4626.994613645115,
  'FHRSID': 783921,
  'LocalAuthorityBusinessID': 'PI/000030119',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME4 6JR',
  'RatigValue': 5,
  'RatingDate': '2015-08-06T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64a9b3f3c5b10300e78af72e'),
  'geocode': {'latitude': Decimal128('51.366103'),
              'longitude': Decimal128('0.517494')},
  'latitude': None,
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/783921',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': 'The Huntsman',
  'AddressLine2': '106 Pattens Lane',
  'AddressLine3': 'Rochester',
  'AddressLine4': 'Medway',
  'BusinessName': 'Que & Brew Smokehouse',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4627.068948009548,
  'FHRSID': 1423359,
  'LocalAuthorityBusinessID': '21/00411/CP',
  'LocalAuthorityCode': '896',
  'LocalAuthorityEmailAddress': 'foodandsafety@medway.gov.uk',
  'LocalAuthorityName': 'Medway',
  'LocalAuthorityWebSite': 'http://www.medway.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME1 2RA',
  'RatigValue': 5,
  'RatingDate': '2022-02-20T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64a9b3f3c5b10300e78af77e'),
  'geocode': {'latitude': Decimal128('51.3666861'),
              'longitude': Decimal128('0.5160458')},
  'latitude': None,
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423359',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}]

In [143]:
# Convert result to Pandas DataFrame



search_df = pd.DataFrame(list(establishments.find(query).sort(sort).limit(limit)))
search_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude,RatigValue
0,64a9b3f3c5b10300e78af77f,802088,0,PI/000251174,Sealand Fish And Chips,Takeaway/sandwich shop,7844,108 Pattens Lane,Rochester,Kent,...,FHRS,"{'longitude': 0.516021, 'latitude': 51.366737}",,4627.071736,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,5
1,64a9b3f3c5b10300e78af780,786158,0,PI/000030142,News Shop,Retailers - other,4613,110 Pattens Lane,Rochester,Kent,...,FHRS,"{'longitude': 0.516021, 'latitude': 51.366737}",,4627.071736,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,5
2,64a9b3f3c5b10300e78af77d,510152,0,PI/000243002,The Huntsman,Pub/bar/nightclub,7843,The Huntsman PH,The Huntsman,106 Pattens Lane,...,FHRS,"{'longitude': 0.5160458, 'latitude': 51.3666861}",,4627.068948,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,5
3,64a9b3f3c5b10300e78af72e,783921,0,PI/000030119,Co-Op,Retailers - other,4613,27-31 Pattens Lane,Chatham,Kent,...,FHRS,"{'longitude': 0.517494, 'latitude': 51.366103}",,4626.994614,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,5
4,64a9b3f3c5b10300e78af77e,1423359,0,21/00411/CP,Que & Brew Smokehouse,Takeaway/sandwich shop,7844,The Huntsman,106 Pattens Lane,Rochester,...,FHRS,"{'longitude': 0.5160458, 'latitude': 51.3666861}",,4627.068948,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,5

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [144]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$LocalAuthorityName", 'count': { '$sum': 1 }}}

# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1 }}
pipeline = [match_query, group_query, sort_values]

# Print the number of documents in the result
results = list(establishments.aggregate(pipeline))
print("Number of countries in result: ", len(results))

# Print the first 10 results
pprint(results[0:10])

Number of countries in result:  55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [145]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame 

rows = len(result_df)
print("Number of rows in DataFrame:", rows)

# Display the first 10 rows of the DataFrame
print("Rows in DataFrame: ", len(result_df))
result_df.head(10)

Number of rows in DataFrame: 55
Rows in DataFrame:  55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542